---
output:
  md_document:
    variant: gfm
---

# argonaut
An R package about dealing with stratified feature tables.

Please note this package is under active development. 

```{r demo}
library(argonaut)
#make some dummy data
sdf <- dummy_strat(2, 3, 4, type = "seq")
 
head(sdf)

#wrangle to stratifiedFeatureTable
as.stratifiedFeatureTable(sdf)


#argonaut is robust to incomplete input, for example when a microbe doesn't have a gene. 
sdf <- dummy_strat(10, 5, 6, type = "by_subtype", p_missing = 0.2)

head(sdf)

head(as.stratifiedFeatureTable(sdf))


```

#Apply_by()
```{r apply_by}
#We can apply a function on the stratifiedFeatureTable with the apply_by() function. 

sft = as.stratifiedFeatureTable(sdf)

#MARGIN must be exactly 1, 2 or 3, corresponding to applying a function on all observations (1) per sample, (2) per feature or (3) per subtype.  

#for example, we can collapse to an unstratified feature table by summing all subtypes of the same feature. 
apply_by(X = sft, MARGIN = 3, FUN = sum)

```

#Running statistical models on stratified feature tables
```{r lm.sft}
library(tidyverse)

y = rnorm(100)

x = dummy_strat(10, 
                nfeatures = 10, 
                nsamples = 100, 
                type = "by_subtype", 
                p_missing = .30) %>% 
  as.sft()

z = sample(LETTERS[1:3], 100, replace = T)


#The getFeature function extracts features by name and returns a table with each subtype of that feature, per sample. 
#getFeatures integrates with models and apply. 

#Run a model with each subtype as a predictor
lm(y ~ getFeature(x, 1) * z) %>% summary

#Run a model for each individual subtype
apply(X      = getFeature(x, 1), 
      MARGIN = 2, 
      FUN    = function(x){lm(y~x) %>% summary})


```